name: penny_smart_wallet
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^23.1.43	
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  auto_route: ^7.8.2
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.2
  animate_do: ^3.1.2
  ionicons: ^0.2.2
  
   



dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1
  build_runner: ^2.2.0
  auto_route_generator: ^7.3.1
  
 
flutter:

  uses-material-design: true
  
  assets:
    - images/

  fonts:
    - family: 's'
      fonts:
        - asset: fonts/Roboto-Regular.ttf
