name: penny_smart_wallet_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^20.2.44
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  animate_do: ^3.1.2
  ionicons: ^0.2.2
  flutter_native_splash: ^2.0.1+1
   
flutter_native_splash:
   color: "#42a5f5"
   android_12:
    image: images/spash3.png
    color: "#ffffff"


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

  
  

flutter:

  uses-material-design: true
  
  assets:
    - images/

  fonts:
    - family: 's'
      fonts:
        - asset: fonts/Roboto-Regular.ttf
